test(edgraph): Remove server_test.go that tested parseRDFs.
chunker.parseRDFs was removed.

    $ go test -v .
    # github.com/outcaste-io/outserv/edgraph [github.com/outcaste-io/outserv/edgraph.test]
    ./server_test.go:51:17: undefined: chunker.ParseRDFs
    ./server_test.go:62:15: undefined: chunker.ParseRDFs
    ./server_test.go:68:17: undefined: chunker.ParseRDFs
    ./server_test.go:78:17: undefined: chunker.ParseRDFs
    ./server_test.go:110:18: undefined: chunker.ParseRDFs